name: Trigger Release

on:
  workflow_dispatch:

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not main
        if:
          github.event_name == 'workflow_dispatch' && github.ref !=
          'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1
      - name: Checkout Repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        # We need elevated user permissions to be able to push tags and commits
        # to main (because it's a protected branch) so we use a deploy secret
        # here.
        with:
          ssh-key: ${{ secrets.TAG_PUSH_DEPLOY_KEY }}
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%-Y.%-m.%-d')" | tee -a $GITHUB_OUTPUT
      - name: Get Current Package Version
        id: get-pkg-version
        run: echo "pkg-version=$(npm pkg get version)" | tee -a $GITHUB_OUTPUT
      - name: Get Version for Release
        id: get-release-version
        run: |
          date=${{ steps.get-date.outputs.date }}
          old_version=${{ steps.get-pkg-version.outputs.pkg-version }}
          new_version=$date
          if [[ $old_version == $date ]]; then
            echo "There is already one package published under this date. Adding '-1' at the end"
            new_version=$date-1
          elif [[ $old_version =~ $date-.* ]]; then
            echo "There are already multiple packages published under this date. Bumping last digit"
            # https://stackoverflow.com/questions/4485399/how-can-i-bump-a-version-number-using-bash
            new_version=$(echo $old_version | awk -F- '/[0-9]+\./{$NF++;print}' OFS=-)
          fi
          echo "new-version=$new_version" | tee -a $GITHUB_OUTPUT
      # Pretend the push and tag were done by me
      - name: Setup Git
        run: |
          git config user.name 'Pierre Amelot'
          git config user.email 'pierre.p.amelot@gmail.com'
      - name: Bump Version and Tag
        # add [skip actions] to commit message to prevent unnecessary workflow
        # run from this trivial automated commit
        run: |
          npm version ${{ steps.get-release-version.outputs.new-version }} -m "%s

          [skip actions]"
      - name: Push to main
        run: git push origin main --follow-tags
      - name: Create Github Release
        run: gh release create $(git describe --tags) --generate-notes
        # We need a personal access token here (fine-grained to this repo) to
        # deploy the release. If used GITHUB_TOKEN instead, the production
        # deployment workflow would not get triggered by the release
        # publication.
        # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_CREATION_TOKEN }}
